Repository real-digital/esque, pull requests merged in 2019-09, with the labels that each got.

#40 More extensive travis testing
  .travis.yml
  esque/cli/commands.py
  setup.py
Labels: enhancement

#52 Just moved some stuff around because it felt more logical
  esque/cli/commands.py
  esque/cli/environment.py
  esque/cli/options.py
  esque/cli/output.py
  esque/clients.py
  esque/clients/__init__.py
  esque/clients/consumer.py
  esque/clients/producer.py
  esque/clients/schemaregistry.py
  esque/cluster.py
  esque/config/__init__.py
  esque/controller/__init__.py
  esque/controller/consumergroup_controller.py
  esque/controller/topic_controller.py
  esque/messages/__init__.py
  esque/messages/avromessage.py
  esque/messages/message.py
  esque/resources/__init__.py
  esque/resources/broker.py
  esque/resources/consumergroup.py
  esque/resources/resource.py
  esque/resources/topic.py
  tests/conftest.py
  tests/integration/test_clients.py
  tests/integration/test_consumergroup.py
  tests/integration/test_consumergroup_controller.py
  tests/integration/test_topic.py
  tests/integration/test_topic_controller.py
Labels: refactoring

#56 Ensure described topic exists
  .gitignore
  .travis.yml
  docker-compose.yml
  esque/cli/commands.py
  esque/controller/topic_controller.py
  esque/errors.py
Labels: bug

#54 Add more tests
  esque/cli/commands.py
  esque/clients/consumer.py
  tests/conftest.py
  tests/integration/commands/__init__.py
  tests/integration/commands/test_apply.py
  tests/integration/commands/test_creation.py
  tests/integration/commands/test_deletion.py
  tests/integration/commands/test_describe.py
  tests/integration/commands/test_get.py
  tests/integration/commands/test_ping.py
  tests/integration/test_topic_controller.py
Labels: enhancement

#76 added method for local topics
  esque/cli/commands.py
  esque/controller/topic_controller.py
Labels: bug
