Repository real-digital/esque, pull requests merged in 2019-11, with the labels that each got.

#95 94 fix autocompletion installation
  esque/cli/commands.py
  pyproject.toml
  scripts/auto_completion.sh
Labels: enhancement

#97 Improve error handling
  esque/cli/commands.py
  esque/cli/environment.py
  esque/cli/helpers.py
  esque/cli/options.py
  esque/clients/consumer.py
  esque/clients/producer.py
  esque/cluster.py
  esque/config/__init__.py
  esque/controller/consumergroup_controller.py
  esque/controller/topic_controller.py
  esque/errors.py
  esque/helpers.py
  esque/messages/message.py
  esque/resources/broker.py
  tests/conftest.py
  tests/integration/commands/test_apply.py
  tests/integration/commands/test_creation.py
  tests/integration/commands/test_deletion.py
  tests/integration/commands/test_describe.py
  tests/integration/commands/test_edit.py
Labels: enhancement

#99 Autocomplete script bugfix.
  esque/cli/commands.py
Labels: bug

#96 65 improve config
  .pre-commit-config.yaml
  esque/cli/commands.py
  esque/cli/helpers.py
  esque/cli/options.py
  esque/config/__init__.py
  esque/config/migration.py
  esque/config/sample_config.cfg
  esque/config/sample_config.yaml
  esque/controller/topic_controller.py
  esque/errors.py
  esque/validation/__init__.py
  esque/validation/schemas/esque_config.yaml
  esque/validation/yamale_validators.py
  pyproject.toml
  tests/conftest.py
  tests/integration/commands/conftest.py
  tests/integration/commands/test_apply.py
  tests/integration/commands/test_creation.py
  tests/integration/commands/test_deletion.py
  tests/integration/commands/test_describe.py
  tests/integration/commands/test_edit.py
  tests/integration/commands/test_get.py
  tests/integration/commands/test_ping.py
  tests/test_configs/integration_test_config.yaml
  tests/test_configs/v0_sample.cfg
  tests/test_configs/v1_sample.yaml
  tests/unit/commands/__init__.py
  tests/unit/commands/conftest.py
  tests/unit/commands/test_config.py
  tests/unit/test_config.py
  tests/unit/validators/test_editable_topic.py
  tests/unit/validators/test_esque_config.py
  tests/unit/validators/test_topic.py
Labels: enhancement

#102 Adds consumergroup option for consume command
  esque/cli/commands.py
Labels: enhancement

#98 Edit offset for consumergroup
  .pre-commit-config.yaml
  esque/cli/commands.py
  esque/cli/helpers.py
  esque/clients/consumer.py
  esque/cluster.py
  esque/config/__init__.py
  esque/controller/consumergroup_controller.py
  esque/controller/topic_controller.py
  esque/errors.py
  esque/messages/message.py
  esque/resources/consumergroup.py
  esque/ruleparser/fieldeval.py
  esque/validation/schemas/esque_config.yaml
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/integration/commands/test_apply.py
  tests/integration/commands/test_consume.py
  tests/integration/commands/test_creation.py
  tests/integration/commands/test_deletion.py
  tests/integration/commands/test_describe.py
  tests/integration/commands/test_edit.py
  tests/integration/commands/test_get.py
  tests/integration/commands/test_ping.py
  tests/integration/test_clients.py
  tests/integration/test_consumergroup_controller.py
  tests/unit/test_output.py
  tests/unit/validators/test_esque_config.py
Labels: enhancement

#108 Some readme improvements
  README.md
Labels: documentation

#80 61 installation and packaging
  .github/workflows/release.yml
  .github/workflows/testing.yml
  .travis.yml
  esque/__init__.py
  esque/cli/commands.py
  esque/clients/consumer.py
  esque/clients/producer.py
  esque/errors.py
  esque/helpers.py
  kafka.Dockerfile
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/integration/commands/test_ping.py
Labels: enhancement

#115 Adds new Github Actions badge
  .github/workflows/testing.yml
  README.md
Labels: documentation

#105 100 improve context help text
  README.md
  esque/cli/commands.py
  esque/cli/options.py
  esque/clients/consumer.py
  esque/clients/producer.py
  esque/controller/consumergroup_controller.py
  esque/controller/topic_controller.py
  esque/errors.py
  tests/integration/commands/test_describe.py
  tests/integration/commands/test_edit.py
  tests/integration/commands/test_produce.py
  tests/integration/test_clients.py
Labels: enhancement

#82 Get last message time
  esque/clients/consumer.py
  esque/controller/topic_controller.py
  esque/resources/topic.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#124 Adds coveralls
  .github/workflows/testing.yml
  README.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#126 Use default timeout for consume
  esque/clients/consumer.py
  esque/controller/topic_controller.py
  esque/resources/topic.py
Labels: bug
